---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  browser: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  # https://github.com/benmosher/eslint-plugin-import
  - import

extends:
  - 'airbnb-base'

rules:
  no-console: 0